---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycm
data:
  aa: bb
  bb: cc
  dd: ee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1-alpine
        command: ["/bin/bash", "-lec", "aaa; while true ; do sleep 1 ; done"]
        ports:
        - containerPort: 81
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu:18.04
        command: ["/bin/bash", "-lec", "for i in {1..20}; do date; sleep 1 ; done"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: synchronization-sticky
spec:
  rules:
  - host: synchronization.werf.io
    http:
      paths:
      - backend:
          serviceName: synchronization-v1
          servicePort: 80
        path: /
  tls:
  - hosts:
    - synchronization.werf.io
    secretName: tls-synchronization.werf.io

